name: ngs-environment
channels:
  - conda-forge
  - ngsolve
  - pyviz
dependencies:
  - python=3.7
  - ngsolve-nogui
  - bokeh
  - pyviz_comms
  - panel
  - lxml
  - cmake
  - clang
  - pybind11 
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - scipy
    - numpy
    - pyct
    - git+https://github.com/regpy/regpy.git@release
    - matplotlib

        
