name: ngsolve-test-environment
channels:
  - anaconda
  - conda-forge
  - ngsolve
  - pyviz
dependencies:
  - python=3.7
  - ngsolve-nogui
  - numpy
  - matplotlib
  - scipy
  - itkwidgets
  - vtk
  - pyviz_comms
  - panel
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - git+https://github.com/regpy/regpy.git@release
