name: ngsolve-test-environment
channels:
  - anaconda
  - conda-forge
  - ngsolve
  - pyviz
dependencies:
  - ngsolve-nogui
  - numpy
  - matplotlib
  - scipy
  - itkwidgets
  - vtk
  - pyvista
  - panel
  - cmake
  - clang